#!/usr/bin/env -S python3 -B
import argparse
import connect
import sys

def main():
    parser = argparse.ArgumentParser(add_help=False, description='Connect. Like your dots?', usage='%(prog)s IP PORT [--help, --ssl, --verbose]')
    parser.add_argument('--help', action='help', help='Show this help message and exits.')
    parser.add_argument('IP', type=str, help='The internet protocol address to use.')
    parser.add_argument('PORT', type=int, help='The port to use.')
    parser.add_argument('--ssl', nargs=2, metavar=('CERT', 'KEY'), help='Use SSL.')
    args=parser.parse_args()
    return connect.run(args)

if __name__ == '__main__':
    sys.exit(main())
