class Config:
    TEMPLATES_AUTO_RELOAD = True
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = '463f1eabe8f830653b2ffd8a89cd1272'
    SQLALCHEMY_DATABASE_URI = 'sqlite:///connect.db'
    JSON_SORT_KEYS = False
